#ifndef Unit10H
#define Unit10H
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <ComCtrls.hpp>
#include <Mask.hpp>
#include <Buttons.hpp>
#include <Grids.hpp>
#include <QRCtrls.hpp>
#include <QuickRpt.hpp>
#include <DateUtils.hpp>
class TForm10 : public TForm
{
__published:	// IDE-managed Components
    TPanel *Panel1;
    TPanel *Panel2;
    TLabel *Label1;
    TLabel *Label2;
    TEdit *Edit1;
    TLabel *Label3;
    TLabel *Label4;
    TLabel *Label5;
    TLabel *Label6;
    TLabel *Label7;
    TEdit *Edit3;
    TEdit *Edit4;
    TEdit *Edit5;
    TLabel *Label8;
    TEdit *Edit6;
    TDateTimePicker *DateTimePicker1;
    TLabel *Label9;
    TComboBox *ComboBox2;
    TLabel *Label10;
    TComboBox *ComboBox1;
    TLabel *Label11;
    TLabel *Label12;
    TEdit *Edit7;
    TEdit *Edit8;
    TLabel *Label13;
    TEdit *Edit2;
    TLabel *Label14;
    TGroupBox *GroupBox1;
    TLabel *Label15;
    TEdit *Edit9;
    TLabel *Label16;
    TLabel *Label17;
    TEdit *Edit10;
    TDateTimePicker *DateTimePicker2;
    TGroupBox *GroupBox2;
    TLabel *Label18;
    TLabel *Label19;
    TLabel *Label20;
    TDateTimePicker *DateTimePicker3;
    TEdit *Edit11;
    TEdit *Edit12;
    TLabel *Label21;
    TEdit *Edit13;
    TLabel *Label22;
    TEdit *Edit14;
    TMaskEdit *MaskEdit1;
    TLabel *Label23;
    TLabel *Label24;
    TLabel *Label25;
    TEdit *Edit15;
    TStringGrid *StringGrid1;
    TLabel *Label26;
    TEdit *Edit16;
    TLabel *Label27;
    TEdit *Edit17;
    TLabel *Label28;
    TStringGrid *StringGrid2;
    TGroupBox *GroupBox3;
    TLabel *Label30;
    TDateTimePicker *DateTimePicker4;
    TStringGrid *StringGrid4;
    TQRShape *QRShape1;
    TLabel *Label31;
    TLabel *Label32;
    TLabel *Label33;
    TQRShape *QRShape2;
    TQRShape *QRShape3;
    TQRShape *QRShape4;
    TQRShape *QRShape5;
    TGroupBox *GroupBox5;
    TStringGrid *StringGrid5;
    TGroupBox *GroupBox4;
    TLabel *Label34;
    TLabel *Label35;
    TLabel *Label36;
    TLabel *Label37;
    TLabel *Label38;
    TLabel *Label39;
    TLabel *Label40;
    TLabel *Label41;
    TLabel *Label42;
    TLabel *Label43;
    TLabel *Label44;
    TComboBox *ComboBox3;
    TEdit *Edit18;
    TEdit *Edit19;
    TComboBox *ComboBox4;
    TEdit *Edit20;
    TEdit *Edit21;
    TEdit *Edit22;
    TEdit *Edit23;
    TEdit *Edit24;
    TEdit *Edit25;
    TSpeedButton *SpeedButton1;
    TSpeedButton *SpeedButton2;
    TGroupBox *GroupBox6;
    TSpeedButton *SpeedButton3;
    TSpeedButton *SpeedButton4;
    TStringGrid *StringGrid6;
    TLabel *Label45;
    TLabel *Label46;
    TLabel *Label47;
    TQRShape *QRShape6;
    TQRShape *QRShape7;
    TQRShape *QRShape8;
    TQRShape *QRShape9;
    TQRShape *QRShape10;
    TLabel *Label48;
    TQRShape *QRShape11;
    TQRShape *QRShape12;
    TQRShape *QRShape13;
    TLabel *Label49;
    TQRShape *QRShape14;
    TLabel *Label50;
    TGroupBox *GroupBox7;
    TLabel *Label51;
    TLabel *Label52;
    TLabel *Label53;
    TLabel *Label54;
    TLabel *Label55;
    TLabel *Label56;
    TQRShape *QRShape15;
    TQRShape *QRShape16;
    TQRShape *QRShape17;
    TQRShape *QRShape18;
    TQRShape *QRShape19;
    TQRShape *QRShape20;
    TQRShape *QRShape21;
    TStringGrid *StringGrid7;
    TQRShape *QRShape22;
    TLabel *Label57;
    TQRShape *QRShape23;
    TQRShape *QRShape24;
    TLabel *Label58;
    TLabel *Label59;
    TQRShape *QRShape25;
    TQRShape *QRShape26;
    TLabel *Label60;
    TPanel *Panel3;
    TGroupBox *GroupBox9;
    TLabel *Label71;
    TLabel *Label72;
    TLabel *Label73;
    TLabel *Label74;
    TLabel *Label78;
    TSpeedButton *SpeedButton7;
    TSpeedButton *SpeedButton8;
    TQRShape *QRShape39;
    TQRShape *QRShape40;
    TQRShape *QRShape42;
    TQRShape *QRShape44;
    TQRShape *QRShape45;
    TStringGrid *StringGrid9;
    TQRShape *QRShape46;
    TQRShape *QRShape49;
    TQRShape *QRShape50;
    TGroupBox *GroupBox10;
    TLabel *Label69;
    TLabel *Label76;
    TLabel *Label77;
    TLabel *Label79;
    TSpeedButton *SpeedButton9;
    TSpeedButton *SpeedButton10;
    TQRShape *QRShape41;
    TQRShape *QRShape43;
    TQRShape *QRShape47;
    TQRShape *QRShape48;
    TQRShape *QRShape51;
    TStringGrid *StringGrid10;
    TQRShape *QRShape53;
    TQRShape *QRShape52;
    TQRShape *QRShape55;
    TQRShape *QRShape56;
    TQRShape *QRShape54;
    TQRShape *QRShape57;
    TLabel *Label75;
    TLabel *Label80;
    TLabel *Label81;
    TLabel *Label82;
    TLabel *Label83;
    TQRShape *QRShape58;
    TMemo *Memo1;
    TGroupBox *GroupBox11;
    TLabel *Label84;
    TLabel *Label85;
    TLabel *Label86;
    TLabel *Label87;
    TSpeedButton *SpeedButton11;
    TSpeedButton *SpeedButton12;
    TLabel *Label88;
    TQRShape *QRShape59;
    TQRShape *QRShape60;
    TQRShape *QRShape62;
    TQRShape *QRShape63;
    TStringGrid *StringGrid11;
    TQRShape *QRShape64;
    TQRShape *QRShape65;
    TQRShape *QRShape68;
    TQRShape *QRShape70;
    TLabel *Label93;
    TSpeedButton *SB_Left;
    TSpeedButton *SB_Right;
    TSpeedButton *SB_Save1;
    TSpeedButton *SB_Save2;
    TPanel *Panel4;
    TLabel *Label89;
    TMemo *Memo2;
    TLabel *Label90;
    TLabel *Label91;
    TMemo *Memo3;
    TLabel *Label92;
    TMemo *Memo4;
    TLabel *Label94;
    TMemo *Memo5;
    TLabel *Label95;
    TMemo *Memo6;
    TLabel *Label96;
    TMemo *Memo7;
    TLabel *Label97;
    TMemo *Memo8;
    TLabel *Label98;
    TMemo *Memo9;
    TLabel *Label100;
    TLabel *Label99;
    TDateTimePicker *DateTimePicker5;
    TLabel *Label101;
    TLabel *Label102;
    TLabel *Label103;
    TLabel *Label104;
    TLabel *Label105;
    TQRShape *QRShape61;
    TQRShape *QRShape66;
    TQRShape *QRShape67;
    TQRShape *QRShape69;
    TQRShape *QRShape71;
    TQRShape *QRShape72;
    TQRShape *QRShape73;
    TQRShape *QRShape74;
    TQRShape *QRShape75;
    TLabel *Label106;
    TLabel *Label107;
    TStringGrid *StringGrid3;
    TLabel *Label29;
    TGroupBox *GroupBox8;
    TLabel *Label61;
    TLabel *Label62;
    TLabel *Label63;
    TLabel *Label64;
    TLabel *Label65;
    TLabel *Label66;
    TLabel *Label67;
    TLabel *Label68;
    TLabel *Label70;
    TSpeedButton *SpeedButton5;
    TSpeedButton *SpeedButton6;
    TQRShape *QRShape27;
    TQRShape *QRShape28;
    TQRShape *QRShape29;
    TQRShape *QRShape30;
    TQRShape *QRShape31;
    TQRShape *QRShape32;
    TQRShape *QRShape33;
    TStringGrid *StringGrid8;
    TQRShape *QRShape34;
    TQRShape *QRShape35;
    TQRShape *QRShape36;
    TQRShape *QRShape38;
    TQRShape *QRShape37;
    TLabel *Label108;
    TLabel *Label109;
    TLabel *Label110;
    TLabel *Label111;
    TLabel *Label112;
    TLabel *Label113;
    TLabel *Label114;
    TQRShape *QRShape76;
    TQRShape *QRShape77;
    TQRShape *QRShape78;
    TQRShape *QRShape79;
    TQRShape *QRShape80;
    TQRShape *QRShape81;
    TQRShape *QRShape82;
    TQRShape *QRShape83;
    TQRShape *QRShape84;
    TLabel *Label115;
    TDateTimePicker *DateTimePicker6;
    TQRShape *QRShape85;
    TLabel *Label116;
    TLabel *Label_NewD;
    void __fastcall FormCreate(TObject *Sender);
    void __fastcall FormShow(TObject *Sender);
    void __fastcall Edit13KeyPress(TObject *Sender, char &Key);
    void __fastcall Edit14KeyPress(TObject *Sender, char &Key);
    void __fastcall ComboBox3KeyPress(TObject *Sender, char &Key);
    void __fastcall ComboBox4KeyPress(TObject *Sender, char &Key);
    void __fastcall SpeedButton1Click(TObject *Sender);
    void __fastcall SpeedButton2Click(TObject *Sender);
    void __fastcall SpeedButton3Click(TObject *Sender);
    void __fastcall SpeedButton4Click(TObject *Sender);
    void __fastcall SpeedButton5Click(TObject *Sender);
    void __fastcall SpeedButton6Click(TObject *Sender);
    void __fastcall SpeedButton7Click(TObject *Sender);
    void __fastcall SpeedButton8Click(TObject *Sender);
    void __fastcall SpeedButton9Click(TObject *Sender);
    void __fastcall SpeedButton11Click(TObject *Sender);
    void __fastcall SpeedButton12Click(TObject *Sender);
    void __fastcall SpeedButton10Click(TObject *Sender);
    void __fastcall SB_LeftClick(TObject *Sender);
    void __fastcall SB_RightClick(TObject *Sender);
    void __fastcall Edit16Exit(TObject *Sender);
    void __fastcall Edit1Change(TObject *Sender);
    void __fastcall Edit3Change(TObject *Sender);
    void __fastcall Edit5Change(TObject *Sender);
    void __fastcall Edit6Change(TObject *Sender);
    void __fastcall Edit7Change(TObject *Sender);
    void __fastcall ComboBox1Change(TObject *Sender);
    void __fastcall Edit9Change(TObject *Sender);
    void __fastcall Edit10Change(TObject *Sender);
    void __fastcall Edit11Change(TObject *Sender);
    void __fastcall Edit12Change(TObject *Sender);
    void __fastcall Edit15Change(TObject *Sender);
    void __fastcall Edit16Change(TObject *Sender);
    void __fastcall Edit17Change(TObject *Sender);
    void __fastcall Edit18Change(TObject *Sender);
    void __fastcall Edit19Change(TObject *Sender);
    void __fastcall Edit20Change(TObject *Sender);
    void __fastcall Edit21Change(TObject *Sender);
    void __fastcall Edit22Change(TObject *Sender);
    void __fastcall Edit23Change(TObject *Sender);
    void __fastcall Edit24Change(TObject *Sender);
    void __fastcall Edit25Change(TObject *Sender);
    void __fastcall Memo2Change(TObject *Sender);
    void __fastcall Memo3Change(TObject *Sender);
    void __fastcall Memo4Change(TObject *Sender);
    void __fastcall Memo5Change(TObject *Sender);
    void __fastcall Memo6Change(TObject *Sender);
    void __fastcall Memo8Change(TObject *Sender);
    void __fastcall Memo9Change(TObject *Sender);
    void __fastcall Edit4Change(TObject *Sender);
    void __fastcall StringGrid1DrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
    void __fastcall StringGrid4DrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
    void __fastcall StringGrid5DrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
    void __fastcall StringGrid4KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid4Exit(TObject *Sender);
    void __fastcall StringGrid1KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid2KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid3KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid5KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid6KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid7KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid8KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid9KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid10KeyPress(TObject *Sender, char &Key);
    void __fastcall StringGrid11KeyPress(TObject *Sender, char &Key);
    void __fastcall ComboBox2KeyPress(TObject *Sender, char &Key);
    void __fastcall SB_Save1Click(TObject *Sender);
    void __fastcall StringGrid5Enter(TObject *Sender);
    void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
    void __fastcall MaskEdit1KeyPress(TObject *Sender, char &Key);
    void __fastcall ComboBox3Select(TObject *Sender);
    void __fastcall ComboBox4Select(TObject *Sender);
    void __fastcall ComboBox2Select(TObject *Sender);
private:	// User declarations
public:		// User declarations
    __fastcall TForm10(TComponent* Owner);
    int forwhat;
};
extern PACKAGE TForm10 *Form10;
#endif
 